blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	#ex: /blog/
	url(r'^$', views.index, name='index'),

	#ex: /blog/view
	url(r'^blog/view(?P<slug>[^\.]+)/$', views.view_post, name='blog_post'),

	#ex /blog/category
	url(r'^blog/category(?P<slug>[^\.]+)/$', views.view_category, name='blog_category'),




]

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	url(r'^$', views.index, name='index'),

	#ex: /about_me
	url(r'^about_me/$', views.about_me, name='about_me'),

	#ex: /resume
	url(r'^resume/$', views.resume, name='resume'),

	#ex: /contact
	url(r'^contact/$', views.contact, name='contact'),

	#ex: /contact/thanks
	url(r'^contact/thanks/$', views.contact, name='contact_thanks'),

	#ex: /projects
	url(r'^projects/$', views.projects, name='projects'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import render

handler404 = 'home.views.bad_request'

urlpatterns = [
    url(r'^polls/', include('polls.urls',namespace='polls')),
	url(r'^pokemon/', include('pokemon.urls',namespace='pokemon')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'', include('home.urls', namespace='home')),
]

pokemon/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#ex: /pokemon/
	url(r'^$', views.index, name='index'),

	#ex: /pokemon/157
	url(r'^(?P<pokedex_number>[0-9]+)/$', views.details, name='details')

	
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#ex: /polls/
	url(r'^$', views.IndexView.as_view(), name='index'),

	#ex: /polls/5/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

	#ex: /polls/5/results
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),

	#ex: /polls/5/vote/
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

blog/models.py
from django.db import models
from django.db.models import permalink

# Create your models here.
class Blog(models.Model):
	title = models.CharField(max_length=100, unique=True)
	slug = models.SlugField(max_length=100, unique=True)
	body = models.TextField()
	posted = models.DateTimeField(db_index=True, auto_now_add=True)
	category = models.ForeignKey('blog.Category')

	def __str__(self):
		return self.title

	@permalink
	def get_absolute_url(self):
		return ('view_blog_post', None, {'slug': self.slug })

class Category(models.Model):
	title = models.CharField(max_length=100, db_index=True)
	slug = models.SlugField(max_length=100, db_index=True)

	def __str__(self):
		return self.title

	@permalink
	def get_absolute_url(self):
		return ('view_blog_category', None, { 'slug': self.slug })

home/models.py
from django.db import models

# Create your models here.

class User(models.Model):
	full_name = models.CharField(max_length=33)
	job_title = models.CharField(max_length=50)
	age = models.IntegerField(default=0)

pokemon/models.py
from django.db import models

# Create your models here.
class Pokemon(models.Model):
	name = models.CharField(max_length=33)
	type1 = models.CharField(max_length=10)
	type2 = models.CharField(max_length=33)
	pokedex_number = models.IntegerField()
	description = models.TextField(default="(no description)")

	def __str__(self):
		return self.name

polls/models.py
import datetime

from django.db import models

from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now-datetime.timedelta(days=1) <= self.pub_date <= now
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog, Category

# Create your views here.

def index(request):
	context = { 
		'categories': Category.objects.all(),
		'posts': Blog.objects.all()[:5],
	}
	return render(request, 'blog/index.html', context)

def view_post(request, slug):
	context = { 'post': get_object_or_404(Blog, slug=slug) }
	return render(request, 'blog/view_post.html', context)

def view_category(request, slug):
	category = get_object_or_404(Category, slug=slug)
	context = { 'category': category,
				'posts': Blog.objects.filter(category=category)[:5] 
			}
	return render(request, 'blog/view_category.html', context)

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import send_mail

from .form import ContactForm
#Create your views here

def index(request):
	return render(request, 'home/index.html')

def about_me(request):
	return render(request, 'home/about_me.html')

def projects(request):
	return render(request, 'home/projects.html')

def bad_request(request):
	return render(request, "home/error_pages/404.html")

def resume(request):
	with open('home/static/home/images/ca_website_resume.pdf', 'r') as pdf:
		response = HttpResponse(pdf.read(), content_type='application/pdf')
		response['Content-Disposition'] = 'filename=cesar_acosta_resume.pdf'
		return response
	pdf.closed

def contact(request):	
	# If this is a POST request we need to process the form data
	if request.method == 'POST':
		#Create a form instance and populate it with data from the request:
		form = ContactForm(request.POST)
		# check whether it's valid:
		if form.is_valid():
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			sender = form.cleaned_data['sender']

			context = {'subject':subject, 'message':message, 'sender':sender }
			#recepients = ['']

			return render(request, 'home/contact/thanks.html', context)
	else:
		form = ContactForm()
		return render(request, 'home/contact.html', {'form': form})

pokemon/views.py
from django.shortcuts import render, get_object_or_404

from .models import Pokemon

# Create your views here.
def index(request):
	pokemon_list = Pokemon.objects.order_by('pokedex_number')[:20]
	context = {'pokemon_list': pokemon_list}
	return render(request, "pokemon/index.html", context)

def details(request, pokedex_number):
	pokemon = get_object_or_404(Pokemon, pokedex_number=int(pokedex_number))
	response = "You have selected %s<br>" % pokemon.pokedex_number
	if(pokemon.pokedex_number == 157):
		response += "This is my favorite pokemon!"
	context = {
				'response': response, 
				'pokemon_name': pokemon.name, 
				'pokedex_number': pokemon.pokedex_number,
				'description': pokemon.description
			}
	#return HttpResponse(response % Pokemon.objects.get(pokedex_number=pokedex_number))
	return render(request, 'pokemon/details.html', context)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice
# Create your views here.

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Question.objects.filter(
			pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
		

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

def vote(request, question_id):
	p = get_object_of_404(Question, pk=question_id)
	try:
		selected_choice=p.choice_set.get(pk=request.POST['choice'])
	except(KeyError, Choice.DoesNotExist):
		#Redisplay the question voting form
		return render(request, 'polls/detail.html', { 	'question': p,
														'error_message': "You didn't select a choice."
													})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a user
		# hits the Back button
		return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

blog/templates/blog/index.html
{% extends 'home/layouts/base.html' %}
{% block title %}Cesar's Blog{% endblock %}

{% block content %}
	<h2>Categories</h2>
	{% if categories %}
		<ul>
		{% for category in categories %}
			<li><h3><a href="{% url 'blog:blog_category' category.slug %}">{{ category.title }}</a></h3></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>There are no posts.</p>
	{% endif %}

	<h2>Posts</h2>
	{% if posts %}
		<table class="table">		
			<th>Post</th>
			<th>Date Posted</th>
		{% for post in posts reversed %}
		<tr>
			<td><a href="{% url 'blog:blog_post' post.slug %}">{{ post.title }}</a></td>
			<td>{{ post.posted|date:"Y/m/d" }}</td>
		</tr>
		{% endfor %}
		</table>
	{% else %}
		<p>There are no posts.</p>
	{% endif %}

{% endblock %}

blog/templates/blog/view_category.html
{% extends 'home/layouts/base.html' %}
{% block title %}{{ category.title }}{% endblock %}

{% block content %}
	<h1>{{ category.title }}</h1>
	{% if posts %}
		<table class="table">		
			<th>Post</th>
			<th>Date Posted</th>
		{% for post in posts reversed %}
		<tr>
			<td><a href="{% url 'blog:blog_post' post.slug %}">{{ post.title }}</a></td>
			<td>{{ post.posted|date:"Y/m/d" }}</td>
		</tr>
		{% endfor %}
		</table>
	{% else %}
		<p>There are no posts.</p>
	{% endif %}
{% endblock %}

blog/templates/blog/view_post.html
{% extends 'home/layouts/base.html' %}
{% load tz %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}

	<h1>{{ post.title }}</h1>
	<p class="content">{{ post.body }}</p><br />

	{% timezone "America/New_York" %}
		<p><span class="glyphicon glyphicon-time"></span> Posted on <b>{{ post.posted|date:"D M j, Y" }}</b> at
		<b>{{ post.posted|date:"g:i:s a T"}}</b></p>
	{% endtimezone %}

{% endblock %}

home/templates/home/about_me.html
{% extends "home/layouts/base.html" %}
{% load staticfiles %}

{% block content %}
	<h1>About Me</h1>
	<hr>
	<div class="post-container">
		<div class="post-thumb">
			<img src="{% static 'home/images/CesarAcosta.jpg' %}" alt="Cesar Acosta" class="profile-image img-responsive pull-left" id="profile_pic">
		</div>
		<div class="post-content">
			<p class="content"><span style="padding-left:5em">My</span> name is Cesar Acosta and I am currently a Senior majoring in Computer Science, minoring in Japanese at the University of Georgia.</p>
		</div>
	</div>
{% endblock %}

home/templates/home/contact.html
{% extends "home/layouts/base.html" %}

{# Load Bootstrap #}
	{% load bootstrap3 %}
	{% bootstrap_css %}
{ # Load javascript, css #}
	{% load staticfiles %}



{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'home/stylesheets/countdown.css' %}" />
<script src="{% static 'home/javascripts/main.js' %}"></script>


<div class="alert alert-info">
	<strong>Reminder!</strong> Don't forget to include your name and other contact information in your message.
</div>
<form action="/contact/thanks/" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	Character Count: <span class="countdown">2500</span><br />
	<input id="submit" type="submit" value="Submit" />
</form>

{% endblock %}

home/templates/home/contact/thanks.html
{% extends "home/layouts/base.html" %}

{% block content %}
<div class="alert alert-success">
	<strong>Success!</strong> Your message was sent successfully
</div>
<strong>Content</strong>
<ul>
	<li><b>Sender:</b> {{ sender }}</li>
	<li><b>Subject:</b> {{ subject }}</li>
	<li><b>Message:</b> {{ message }}</li>
</ul>

{% endblock content%}

home/templates/home/index.html
{% extends "home/layouts/base.html" %}

{% block content %}
	<div class="alert alert-danger">
		<strong>Warning!</strong> Don't forget to remove any personal information such as phone number, address, and other relative information from the resume!
	</div>
	<h1>Welcome to the Root Page!</h1>
{% endblock %}

home/templates/home/layouts/base.html
{# Load Bootstrap #}
	{% load bootstrap3 %}
	{% bootstrap_css %}
{# Include css #}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'home/stylesheets/style.css' %}" />

<!DOCTYPE html>
<html>
	<title>{% block title %}Cesar's Site{% endblock %}</title>
<body class="application_body">
	<div id="header">
		{% include "home/layouts/header.html" %}
	</div>
	<div class="container">
		{% block content %}
		{% endblock content %}
	</div>
	<div id="footer">
		{% include "home/layouts/footer.html" %}
	</div>
</body>
</html>

home/templates/home/layouts/footer.html
<footer class="footer">
	<p id="footer">
		Copyright &copy; Cesar Acosta. All Rights Reserved.
	</p>
	<nav>
		<ul id="footer">
			<li id="footer"><a href="{% url 'home:about_me' %}">About</a></li>
			<li id="footer"><a href="{% url 'home:contact' %}">Contact</a></li>
		</ul>
	</nav>
</footer>

home/templates/home/layouts/header.html
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
	<nav>
		<ul class="nav navbar-nav navbar-left">
			<li><a href="{% url 'home:index' %}">Cesar Acosta</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li><a href="{% url 'home:index' %}">Home</a></li>
			<li><a href="{% url 'blog:index'%}">Blog</a></li>
			<li><a href="{% url 'home:projects' %}">Projects</a></li>
			<li><a href="{% url 'home:resume' %}">Resume</a></li>
			<li><a href="{% url 'pokemon:index' %}">Pokedex</a></li>
		</ul>
	</nav>
	</div>
</header>

home/templates/home/projects.html
{% extends "home/layouts/base.html" %}
{% load staticfiles %}

{% block content %}

	<h1>Projects</h1>

	<h3><a href="https://github.com/cacosta33/Hinky">Hinky</a></h3>
	(<label>C++</label>)
	<p>This is a hangman game with the most basic AI programming, where the computer's goal is to prevent you from winning by changing the guess word.</p>

	<br \>

	<h3><a href="https://github.com/cacosta33/Game_Panel">Game Panel</a></h3>
	(<label>Java</label>)
	<p>This project is a Game Panel that includes the Games Tic-Tac-Toe and a basic version of Tetris, written in Java demonstrating the use of GUI's(Graphical User Interface).</p>

	<br \>

	<h3><a href="https://github.com/cacosta33/Unix_Shell">Unix Shell</a></h3>
	(<label>C++</label>)
	<p>This project is a basic version of the Unix Shell that implements the use of the fundamentals of Systems Programming such as threads, processes, links, pipes, etc.</p>


{% endblock %}

pokemon/templates/pokemon/base.html
{# Load Bootstrap #}
	{% load bootstrap3 %}
	{% bootstrap_css %}

<!DOCTYPE html>
<html>
	<title>{% block title %}Cesar's Site{% endblock %}</title>
<body>
	<div id="content">
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>

pokemon/templates/pokemon/details.html
{# Load Bootstrap #}
	{% load bootstrap3 %}
	{% bootstrap_css %}

{# Load Custom CSS #}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'pokemon/style.css' %}" />

<div id="header">
{% include "home/layouts/header.html" %}
</div>

{% block content %}
<div class="col-md-4 application_body">
	<h1>{{ pokemon_name }}</h1>
	<h2>Pokedex Entry: {{ pokedex_number }}</h2>
	<img src="{% static 'pokemon/images/' %}{{pokedex_number}}.png" alt="{{pokemon_name}}" class="poke"/>
	<p><b>Description:</b><br> {{ description }} </p>
</div>
{% endblock content %}

<div id="footer">
{% include "home/layouts/footer.html" %}
</div>

pokemon/templates/pokemon/index.html
	{% extends "home/layouts/base.html" %}

{% block title%}Pokedex{% endblock %}

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'pokemon/style.css'%}" />

{% block content %}

	<h1>Pokedex</h1>
	{% if pokemon_list %}
			<table class="table table-striped">
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Type 1</th>
			<th>Type 2</th>
		</tr>
		{% for pokemon in pokemon_list %}
			<tr>
				<td>{{ pokemon.pokedex_number|stringformat:"03d" }}</td>
				<td><a href="{% url 'pokemon:details' pokemon.pokedex_number %}">{{ pokemon.name }}
					</a></td>
				<td>{{ pokemon.type1 }}</td>
				{% if pokemon.type2 == "none" %}
					<td>-----</td>
				{% else %}
					<td>{{ pokemon.type2 }}</td>
				{% endif %}
			</tr>
		{% endfor %}
		</table>
	{% else %}
		<p>No pokemon are in the database</p>
	{% endif %}

{% endblock content %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}
</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}"
		value="{{ choice.id}}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }}
	vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>